/*===================================================================
	Descrição:
		--Query para descobrir a fragmentação de todos os índices.
=====================================================================*/

SELECT OBJECT_NAME(IPS.OBJECT_ID) AS [TABLENAME], 
   SI.NAME AS [INDEXNAME], 
   IPS.INDEX_TYPE_DESC, 
   IPS.AVG_FRAGMENTATION_IN_PERCENT, 
   IPS.AVG_FRAGMENT_SIZE_IN_PAGES, 
   IPS.AVG_PAGE_SPACE_USED_IN_PERCENT, 
   IPS.RECORD_COUNT, 
   IPS.GHOST_RECORD_COUNT,
   IPS.FRAGMENT_COUNT, 
   IPS.AVG_FRAGMENT_SIZE_IN_PAGES
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(DB_NAME()), NULL, NULL, NULL , 'DETAILED') IPS
   JOIN SYS.TABLES ST WITH (NOLOCK) ON IPS.OBJECT_ID = ST.OBJECT_ID
   JOIN SYS.INDEXES SI WITH (NOLOCK) ON IPS.OBJECT_ID = SI.OBJECT_ID AND IPS.INDEX_ID = SI.INDEX_ID
WHERE ST.IS_MS_SHIPPED = 0
ORDER BY IPS.AVG_FRAGMENT_SIZE_IN_PAGES DESC;